"use client"

import { useState, useEffect, useRef } from "react"
import { useSearchParams } from "next/navigation"
import Link from "next/link"
import { useAuth } from "@/components/AuthProvider"
import { Zap, Clock, ExternalLink, BookOpen, ArrowRight, RotateCcw } from "lucide-react"

// ── Context pack generator ────────────────────────────────────────────────
function generateContextMd(opts: {
  problem: string
  domainLabel: string
  domainEmoji: string
  actionLabel: string
  actionDesc: string
  stack: Array<{ name: string; href: string; setup: number; category: string }>
  totalSetup: number
}): string {
  const { problem, domainLabel, domainEmoji, actionLabel, actionDesc, stack, totalSetup } = opts
  const stackList = stack
    .sort((a, b) => a.setup - b.setup)
    .map((s, i) => `${i + 1}. **${s.name}** (${s.category}, ~${s.setup}m setup) — ${s.href}`)
    .join("\n")

  return `# Hackathon Context Pack
> Generated by [Codefest.ai](https://codefest.ai) · Load this into your AI assistant before you start building.

---

## The Problem

${problem}

**Domain:** ${domainEmoji} ${domainLabel}
**Core feature:** ${actionLabel} — ${actionDesc}

---

## Your Stack

Set these up in order — each one unblocks the next.

${stackList}

**Total estimated setup time:** ~${totalSetup} minutes

---

## Constraints

- This is a hackathon. Optimize for a working demo, not production quality.
- Timebox each setup item. If you hit 2× the estimate, skip and mock it.
- Build the 3-screen demo path first. Everything else is backlog.
- Use the stack above — don't introduce new tools unless you have a specific reason.

---

## How to Use This File

Paste this entire file as context into your AI assistant at the start of your session.
Then use prompts like:

- *"Given this context, help me scaffold the Next.js project structure"*
- *"What's the fastest way to implement [feature] with the stack above?"*
- *"I'm 4 hours in and [X] isn't working. What should I cut vs. fix?"*
- *"Write the Supabase schema for [my feature] based on this problem statement"*

Your AI now knows your domain, your problem, and your exact stack.

---

## Resources

- Full component library: https://codefest.ai/library
- Stack selection guide: https://codefest.ai/blog/the-default-stack
- Demo scoping guide: https://codefest.ai/blog/build-for-the-demo
- Pre-hackathon checklist: https://codefest.ai/guide

---

*Codefest.ai — the participant-first hackathon infrastructure layer*
`
}

// ── Data ─────────────────────────────────────────────────────────────────

const DOMAINS = [
  { id: "climate",   emoji: "🌱", label: "Climate & Environment" },
  { id: "health",    emoji: "🏥", label: "Health & Wellness" },
  { id: "education", emoji: "📚", label: "Education & Learning" },
  { id: "food",      emoji: "🍎", label: "Food & Agriculture" },
  { id: "finance",   emoji: "💰", label: "Finance & Access" },
  { id: "civic",     emoji: "🏛️", label: "Civic & Community" },
  { id: "safety",    emoji: "🛡️", label: "Safety & Emergency" },
  { id: "transport", emoji: "🚌", label: "Transport & Mobility" },
  { id: "other",     emoji: "✨", label: "Something else" },
]

const CORE_ACTIONS = [
  { id: "map",      icon: "🗺️", label: "Show things on a map",       desc: "Location, routes, proximity, geographic patterns" },
  { id: "form",     icon: "📝", label: "Collect info from users",     desc: "Forms, surveys, multi-step intake, validation" },
  { id: "ai",       icon: "🤖", label: "Answer questions with AI",    desc: "Chat, summarization, classification, generation" },
  { id: "data",     icon: "📊", label: "Visualize data and trends",   desc: "Charts, dashboards, comparisons, time series" },
  { id: "realtime", icon: "💬", label: "Connect people in real-time", desc: "Chat, collaboration, live updates, shared state" },
  { id: "alerts",   icon: "🔔", label: "Send alerts & notifications", desc: "Email, SMS, push notifications, background jobs" },
]

type StackItem = { name: string; href: string; setup: number; category: string }

const STACK_SUGGESTIONS: Record<string, StackItem[]> = {
  map: [
    { name: "Next.js",       href: "https://nextjs.org/docs",                       setup: 5,  category: "framework" },
    { name: "Tailwind CSS",  href: "https://tailwindcss.com/docs",                  setup: 5,  category: "ui" },
    { name: "Supabase",      href: "https://supabase.com/docs",                     setup: 10, category: "database" },
    { name: "react-leaflet", href: "https://react-leaflet.js.org/docs/start-intro", setup: 15, category: "maps" },
  ],
  form: [
    { name: "Next.js",         href: "https://nextjs.org/docs",      setup: 5,  category: "framework" },
    { name: "Tailwind CSS",    href: "https://tailwindcss.com/docs", setup: 5,  category: "ui" },
    { name: "shadcn/ui",       href: "https://ui.shadcn.com",        setup: 10, category: "ui" },
    { name: "Supabase",        href: "https://supabase.com/docs",    setup: 10, category: "database" },
    { name: "React Hook Form", href: "https://react-hook-form.com",  setup: 10, category: "forms" },
    { name: "Zod",             href: "https://zod.dev",              setup: 5,  category: "validation" },
  ],
  ai: [
    { name: "Next.js",       href: "https://nextjs.org/docs",              setup: 5,  category: "framework" },
    { name: "Tailwind CSS",  href: "https://tailwindcss.com/docs",         setup: 5,  category: "ui" },
    { name: "Supabase",      href: "https://supabase.com/docs",            setup: 10, category: "database" },
    { name: "Vercel AI SDK", href: "https://sdk.vercel.ai/docs",           setup: 15, category: "ai" },
    { name: "Groq",          href: "https://console.groq.com/docs/openai", setup: 10, category: "ai" },
  ],
  data: [
    { name: "Next.js",        href: "https://nextjs.org/docs",                             setup: 5,  category: "framework" },
    { name: "Tailwind CSS",   href: "https://tailwindcss.com/docs",                        setup: 5,  category: "ui" },
    { name: "shadcn/ui",      href: "https://ui.shadcn.com",                               setup: 10, category: "ui" },
    { name: "Supabase",       href: "https://supabase.com/docs",                           setup: 10, category: "database" },
    { name: "Recharts",       href: "https://recharts.org/en-US/api",                      setup: 10, category: "charts" },
    { name: "Tanstack Table", href: "https://tanstack.com/table/latest/docs/introduction", setup: 15, category: "tables" },
  ],
  realtime: [
    { name: "Next.js",           href: "https://nextjs.org/docs",                   setup: 5,  category: "framework" },
    { name: "Tailwind CSS",      href: "https://tailwindcss.com/docs",              setup: 5,  category: "ui" },
    { name: "shadcn/ui",         href: "https://ui.shadcn.com",                     setup: 10, category: "ui" },
    { name: "Supabase Realtime", href: "https://supabase.com/docs/guides/realtime", setup: 20, category: "realtime" },
    { name: "Liveblocks",        href: "https://liveblocks.io/docs",                setup: 20, category: "collab" },
  ],
  alerts: [
    { name: "Next.js",      href: "https://nextjs.org/docs",      setup: 5,  category: "framework" },
    { name: "Tailwind CSS", href: "https://tailwindcss.com/docs", setup: 5,  category: "ui" },
    { name: "Supabase",     href: "https://supabase.com/docs",    setup: 10, category: "database" },
    { name: "React Email",  href: "https://react.email/docs",     setup: 10, category: "email" },
    { name: "Resend",       href: "https://resend.com/docs",      setup: 10, category: "email" },
    { name: "Inngest",      href: "https://www.inngest.com/docs", setup: 15, category: "jobs" },
  ],
}

// ── Sub-components ────────────────────────────────────────────────────────

// Connector line between layers
function Connector() {
  return (
    <div className="flex justify-start pl-4 my-1">
      <div className="w-px h-6 bg-white/[0.06]" />
    </div>
  )
}

// Completed layer — compact summary, changeable
function DoneLayer({ label, onReset }: { label: string; onReset: () => void }) {
  return (
    <div className="flex items-center justify-between rounded-xl border border-white/[0.04] bg-surface-0 px-4 py-3">
      <span className="text-sm text-zinc-500">{label}</span>
      <button
        onClick={onReset}
        className="text-xs text-zinc-700 hover:text-zinc-400 transition-colors font-mono"
      >
        change
      </button>
    </div>
  )
}

// Layer wrapper — handles the appear animation
function Layer({ children, id }: { children: React.ReactNode; id?: string }) {
  return (
    <div
      id={id}
      className="animate-in fade-in slide-in-from-bottom-3 duration-200"
    >
      {children}
    </div>
  )
}

// ── Page ─────────────────────────────────────────────────────────────────

export default function WorkspacePage() {
  const { user } = useAuth()
  const searchParams = useSearchParams()
  const pinnedComponent = searchParams.get("add") ?? null
  const domainParam = searchParams.get("domain") ?? null

  // Cascade state — each value being set reveals the next layer
  const [problem,  setProblem]  = useState("")
  const [domain,   setDomain]   = useState<string | null>(
    domainParam && DOMAINS.find(d => d.id === domainParam) ? domainParam : null
  )
  const [action,   setAction]   = useState<string | null>(null)
  const [stack,    setStack]    = useState<string[]>([])
  const [launched, setLaunched] = useState(false)

  // Scroll targets
  const domainRef   = useRef<HTMLDivElement>(null)
  const actionRef   = useRef<HTMLDivElement>(null)
  const stackRef    = useRef<HTMLDivElement>(null)
  const goRef       = useRef<HTMLDivElement>(null)

  // Layer visibility — each unlocks when the one above it is complete
  const showDomain   = problem.trim().length > 0
  const showAction   = showDomain  && domain  !== null
  const showStack    = showAction  && action  !== null
  const showGo       = showStack   && launched

  // Scroll to new layer when it appears
  function scrollTo(ref: React.RefObject<HTMLDivElement>) {
    setTimeout(() => {
      ref.current?.scrollIntoView({ behavior: "smooth", block: "nearest" })
    }, 80)
  }

  useEffect(() => { if (showDomain && domain === null) scrollTo(domainRef) },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [showDomain])
  useEffect(() => { if (showAction && action === null) scrollTo(actionRef) },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [showAction])
  useEffect(() => { if (showStack  && !launched)       scrollTo(stackRef)  },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [showStack])
  useEffect(() => { if (showGo)                        scrollTo(goRef)     },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [showGo])

  // Derived
  const selectedDomain = DOMAINS.find(d => d.id === domain)
  const selectedAction = CORE_ACTIONS.find(a => a.id === action)
  const stackItems     = action ? (STACK_SUGGESTIONS[action] || []) : []
  const selectedItems  = stackItems.filter(s => stack.includes(s.name))
  const pinnedItem: StackItem[] = pinnedComponent && !selectedItems.find(s => s.name === pinnedComponent)
    ? [{ name: pinnedComponent, href: `/library/${pinnedComponent.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, setup: 0, category: "from library" }]
    : []
  const goItems    = [...selectedItems, ...pinnedItem]
  const totalSetup = selectedItems.reduce((sum, s) => sum + s.setup, 0)

  // Resetters — clear downstream state
  function resetFrom(layer: "problem" | "domain" | "action" | "stack") {
    if (layer === "problem") { setProblem(""); setDomain(null); setAction(null); setStack([]); setLaunched(false) }
    if (layer === "domain")  { setDomain(null); setAction(null); setStack([]); setLaunched(false) }
    if (layer === "action")  { setAction(null); setStack([]); setLaunched(false) }
    if (layer === "stack")   { setStack([]); setLaunched(false) }
  }

  function handleSelectDomain(id: string) {
    setDomain(id)
    setAction(null)
    setStack([])
    setLaunched(false)
  }

  function handleSelectAction(id: string) {
    setAction(id)
    setStack((STACK_SUGGESTIONS[id] || []).map(s => s.name))
    setLaunched(false)
  }

  function handleLaunch() {
    setLaunched(true)
  }

  function downloadContextPack() {
    if (!selectedDomain || !selectedAction) return
    const md = generateContextMd({
      problem,
      domainLabel:  selectedDomain.label,
      domainEmoji:  selectedDomain.emoji,
      actionLabel:  selectedAction.label,
      actionDesc:   selectedAction.desc,
      stack:        goItems,
      totalSetup,
    })
    const blob = new Blob([md], { type: "text/markdown" })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement("a")
    a.href     = url
    a.download = "hackathon-context.md"
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-surface-0">

      {/* ── Header ──────────────────────────────────────────────────────── */}
      <header className="fixed top-0 left-0 right-0 z-50 border-b border-white/[0.06] bg-surface-0/90 backdrop-blur-xl">
        <div className="mx-auto flex h-14 max-w-2xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2.5 group">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-500 transition-shadow group-hover:shadow-lg group-hover:shadow-brand-500/25">
              <Zap className="h-4 w-4 text-black" />
            </div>
            <span className="text-lg font-semibold tracking-tight text-white">
              codefest<span className="text-brand-400">.ai</span>
            </span>
          </Link>

          <div className="flex items-center gap-4">
            <span className="font-mono text-[10px] uppercase tracking-widest text-zinc-600">
              workspace
            </span>
            {launched && (
              <button
                onClick={() => resetFrom("problem")}
                className="flex items-center gap-1.5 text-xs text-zinc-600 hover:text-zinc-300 transition-colors"
              >
                <RotateCcw className="h-3 w-3" />
                restart
              </button>
            )}
          </div>
        </div>
      </header>

      {/* ── Cascade ─────────────────────────────────────────────────────── */}
      <main className="mx-auto max-w-2xl px-6 pt-28 pb-32 space-y-0">

        {/* Pinned component banner */}
        {pinnedComponent && (
          <div className="flex items-center gap-3 rounded-xl border border-brand-500/25 bg-brand-500/5 px-4 py-3 mb-6">
            <BookOpen className="h-4 w-4 text-brand-400 shrink-0" />
            <span className="text-xs text-zinc-500">
              <span className="text-brand-400 font-medium">{pinnedComponent}</span>
              {" "}will be added to your stack
            </span>
          </div>
        )}

        {/* ── Layer 0: Problem ──────────────────────────────────────────── */}
        {(domain !== null || !showDomain) ? (
          <DoneLayer
            label={problem.length > 60 ? problem.slice(0, 60) + "…" : problem}
            onReset={() => resetFrom("problem")}
          />
        ) : (
          <Layer id="layer-problem">
            <div className="mb-2">
              <span className="font-mono text-[10px] uppercase tracking-widest text-zinc-600">
                what are you solving?
              </span>
            </div>
            <textarea
              value={problem}
              onChange={e => setProblem(e.target.value)}
              onKeyDown={e => {
                if (e.key === "Enter" && (e.metaKey || e.ctrlKey) && problem.trim()) {
                  domainRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" })
                }
              }}
              placeholder="Who is stuck, and what are they stuck doing?"
              className="w-full rounded-xl border border-white/[0.08] bg-surface-1 px-5 py-4 text-sm text-zinc-200 placeholder-zinc-700 resize-none focus:outline-none focus:border-brand-500/40 transition-colors leading-relaxed"
              rows={3}
              autoFocus
            />
            {problem.trim().length > 0 && (
              <p className="mt-2 text-[11px] text-zinc-700 font-mono">
                pick a domain below ↓
              </p>
            )}
          </Layer>
        )}

        {/* ── Layer 1: Domain ───────────────────────────────────────────── */}
        {showDomain && (
          <>
            <Connector />
            <div ref={domainRef}>
              {(action !== null) ? (
                <DoneLayer
                  label={selectedDomain ? `${selectedDomain.emoji} ${selectedDomain.label}` : "Domain"}
                  onReset={() => resetFrom("domain")}
                />
              ) : (
                <Layer id="layer-domain">
                  <div className="mb-3">
                    <span className="font-mono text-[10px] uppercase tracking-widest text-zinc-600">
                      domain
                    </span>
                  </div>
                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                    {DOMAINS.map(d => (
                      <button
                        key={d.id}
                        onClick={() => handleSelectDomain(d.id)}
                        className={`flex items-center gap-2.5 rounded-xl border px-4 py-3 text-left transition-all group
                          ${domain === d.id
                            ? "border-brand-500/40 bg-brand-500/8 text-white"
                            : "border-white/[0.06] bg-surface-1 text-zinc-400 hover:border-brand-500/25 hover:bg-surface-2 hover:text-zinc-200"
                          }`}
                      >
                        <span className="text-lg shrink-0">{d.emoji}</span>
                        <span className="text-xs font-medium leading-snug">{d.label}</span>
                      </button>
                    ))}
                  </div>
                </Layer>
              )}
            </div>
          </>
        )}

        {/* ── Layer 2: Core Action ──────────────────────────────────────── */}
        {showAction && (
          <>
            <Connector />
            <div ref={actionRef}>
              {launched ? (
                <DoneLayer
                  label={selectedAction ? `${selectedAction.icon} ${selectedAction.label}` : "Action"}
                  onReset={() => resetFrom("action")}
                />
              ) : (
                <Layer id="layer-action">
                  <div className="mb-3">
                    <span className="font-mono text-[10px] uppercase tracking-widest text-zinc-600">
                      what does it do?
                    </span>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {CORE_ACTIONS.map(a => (
                      <button
                        key={a.id}
                        onClick={() => handleSelectAction(a.id)}
                        className={`flex items-start gap-3 rounded-xl border px-4 py-3.5 text-left transition-all group
                          ${action === a.id
                            ? "border-brand-500/40 bg-brand-500/8"
                            : "border-white/[0.06] bg-surface-1 hover:border-brand-500/25 hover:bg-surface-2"
                          }`}
                      >
                        <span className="text-lg shrink-0 mt-0.5">{a.icon}</span>
                        <div>
                          <p className={`text-sm font-medium leading-snug transition-colors ${action === a.id ? "text-white" : "text-zinc-300 group-hover:text-white"}`}>
                            {a.label}
                          </p>
                          <p className="text-xs text-zinc-600 mt-0.5 leading-relaxed">{a.desc}</p>
                        </div>
                      </button>
                    ))}
                  </div>
                </Layer>
              )}
            </div>
          </>
        )}

        {/* ── Layer 3: Stack ────────────────────────────────────────────── */}
        {showStack && (
          <>
            <Connector />
            <div ref={stackRef}>
              {launched ? (
                <DoneLayer
                  label={`${stack.length} component${stack.length !== 1 ? "s" : ""} · ~${totalSetup}min`}
                  onReset={() => resetFrom("stack")}
                />
              ) : (
                <Layer id="layer-stack">
                  <div className="mb-3">
                    <span className="font-mono text-[10px] uppercase tracking-widest text-zinc-600">
                      your stack
                    </span>
                    <span className="ml-3 text-[10px] text-zinc-700">
                      deselect anything you already have
                    </span>
                  </div>
                  <div className="space-y-1.5 mb-4">
                    {stackItems.map(item => {
                      const on = stack.includes(item.name)
                      return (
                        <button
                          key={item.name}
                          onClick={() => setStack(on ? stack.filter(s => s !== item.name) : [...stack, item.name])}
                          className={`w-full flex items-center justify-between rounded-xl border px-4 py-3 text-left transition-all ${
                            on
                              ? "border-brand-500/30 bg-brand-500/5"
                              : "border-white/[0.04] bg-surface-1/40 opacity-35"
                          }`}
                        >
                          <div className="flex items-center gap-3">
                            <div className={`h-4 w-4 rounded border-2 flex items-center justify-center shrink-0 transition-colors ${on ? "border-brand-500 bg-brand-500" : "border-zinc-700"}`}>
                              {on && (
                                <svg className="h-2.5 w-2.5 text-black" viewBox="0 0 10 10" fill="none">
                                  <path d="M2 5l2.5 2.5L8 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                              )}
                            </div>
                            <div>
                              <span className="text-sm text-zinc-200">{item.name}</span>
                              <span className="ml-2 text-xs text-zinc-600">{item.category}</span>
                            </div>
                          </div>
                          <span className="text-xs text-zinc-600 flex items-center gap-1 shrink-0">
                            <Clock className="h-3 w-3" />
                            ~{item.setup}m
                          </span>
                        </button>
                      )
                    })}
                  </div>

                  {/* Total + Go */}
                  <div className="flex items-center justify-between rounded-xl border border-white/[0.06] bg-surface-1 px-4 py-3 mb-4">
                    <span className="text-xs text-zinc-500">estimated setup</span>
                    <span className="font-mono text-sm text-zinc-200">~{totalSetup} min</span>
                  </div>
                  <button
                    onClick={handleLaunch}
                    disabled={stack.length === 0}
                    className="w-full flex items-center justify-center gap-2 rounded-xl bg-brand-500 px-6 py-3.5 text-sm font-semibold text-black hover:bg-brand-400 transition-all disabled:opacity-30 disabled:cursor-not-allowed"
                  >
                    <Zap className="h-4 w-4" />
                    Build this
                  </button>
                </Layer>
              )}
            </div>
          </>
        )}

        {/* ── Layer 4: GO ───────────────────────────────────────────────── */}
        {showGo && (
          <>
            <Connector />
            <div ref={goRef}>
              <Layer id="layer-go">
                {/* Header */}
                <div className="rounded-t-xl border border-b-0 border-brand-500/20 bg-brand-500/[0.04] px-5 py-4">
                  <div className="flex items-center gap-2 mb-1">
                    <Zap className="h-3.5 w-3.5 text-brand-400" />
                    <span className="font-mono text-[10px] uppercase tracking-widest text-brand-500">
                      ready to build
                    </span>
                  </div>
                  <p className="text-xs text-zinc-500 leading-relaxed">{problem}</p>
                </div>

                {/* Stack list */}
                <div className="border border-b-0 border-brand-500/10 bg-surface-1 divide-y divide-white/[0.04]">
                  {goItems
                    .slice()
                    .sort((a, b) => a.setup - b.setup)
                    .map((item, i) => (
                      <a
                        key={item.name}
                        href={item.href}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center justify-between px-5 py-4 hover:bg-surface-2 transition-colors group"
                      >
                        <div className="flex items-center gap-4">
                          <span className="font-mono text-[10px] text-zinc-700 w-4 shrink-0">{i + 1}</span>
                          <div>
                            <p className="text-sm text-zinc-200 group-hover:text-white transition-colors">{item.name}</p>
                            <p className="text-xs text-zinc-600">{item.category}</p>
                          </div>
                        </div>
                        <div className="flex items-center gap-3 shrink-0">
                          <span className="text-xs text-zinc-600 flex items-center gap-1">
                            <Clock className="h-3 w-3" />
                            ~{item.setup}m
                          </span>
                          <ExternalLink className="h-3.5 w-3.5 text-zinc-700 group-hover:text-zinc-400 transition-colors" />
                        </div>
                      </a>
                    ))}
                </div>

                {/* Footer — total + export */}
                <div className="rounded-b-xl border border-brand-500/10 bg-surface-1 px-5 py-4 flex items-center justify-between">
                  <span className="text-xs text-zinc-500 flex items-center gap-1.5">
                    <Clock className="h-3.5 w-3.5" />
                    ~{totalSetup} min total setup
                  </span>
                  <button
                    onClick={downloadContextPack}
                    className="flex items-center gap-2 rounded-lg bg-brand-500 px-4 py-2 text-xs font-semibold text-black hover:bg-brand-400 transition-all"
                  >
                    <BookOpen className="h-3.5 w-3.5" />
                    Export context pack
                  </button>
                </div>

                {/* Secondary actions */}
                <div className="mt-4 flex flex-wrap gap-2">
                  {!user && (
                    <Link
                      href="/login"
                      className="rounded-lg border border-brand-500/30 px-4 py-2 text-xs text-brand-400 hover:bg-brand-500/10 transition-colors"
                    >
                      Save this plan →
                    </Link>
                  )}
                  <Link
                    href="/library"
                    className="rounded-lg border border-white/[0.08] px-4 py-2 text-xs text-zinc-400 hover:text-white hover:border-white/20 transition-colors"
                  >
                    Browse full library
                  </Link>
                  <button
                    onClick={() => resetFrom("problem")}
                    className="rounded-lg border border-white/[0.06] px-4 py-2 text-xs text-zinc-600 hover:text-zinc-400 transition-colors flex items-center gap-1.5"
                  >
                    <RotateCcw className="h-3 w-3" />
                    Start over
                  </button>
                </div>
              </Layer>
            </div>
          </>
        )}
      </main>
    </div>
  )
}
